export const ExpenseCategories = [
  'Housing',
  'Transportation',
  'Groceries',
  'Healthcare',
  'Utilities',
  'Dining Out',
  'Entertainment',
  'Shopping',
  'Debt Payments',
  'Savings and Investments',
  'Travel',
  'Insurance',
  'Education',
  'Childcare',
  'Charity and Donations',
  'Taxes',
  'Pet Expenses',
  'Personal Care',
  'Home Office',
  'Miscellaneous',
] as const;
